CREATE DATABASE tasksdb

CREATE TABLE tasks (
  id INTEGER PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
);

CREATE TABLE users (
  user_id INTEGER PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

ALTER TABLE tasks

ADD COLUMN user_id INTEGER NOT NULL REFERENCES users(user_id);
